### ISSUE TITLE
不需要url保活和需要有什么区别呢？

### ISSUE THREAD

**Issue by 3377** [zhuifan1/koyeb-alive#1]
一般用哪个比较合适呀

**Comment by zhuifan1** [comment]
因为大多数容器都会闲置自动暂停，需要间隔一段时间访问一下才一直保活，如果你用了uptimerobot之类的监控就不需要保活，每天跑一次脚本即可

**Comment by 3377** [comment]
额、koyeb的保活机制不是14天要登录一次面板吗？这个访问容器可以保活吗😂

**Comment by zhuifan1** [comment]
这个脚本的逻辑是检测状态是否异常，如果异常就恢复，严格来讲不算保活脚本，url激活只是我顺便加上去适配其他容器，如果不需要的话直接简单粗暴使用release的初代版本，无论是否异常都尝试恢复，这样就可以不需要登录面板了(因为我也是小号,密码早忘了)
脚本并不消耗性能(只是访问一下链接)，哪怕一分钟跑一次都感知不到性能消耗，1天跑一次理论最长宕机24小时，一分钟跑一次最长宕机1分钟

**Comment by 3377** [comment]
好的、谢谢讲解、我这的需求其实就是保证koyeb这个账号下的容器能正常一直使用、如果异常了再去恢复是不是晚了点呀😀那我直接跑 release.14天内一次是否即可

**Comment by zhuifan1** [comment]
可以，实际上我也是7天跑一次，1个月了都没被暂停

**Comment by 3377** [comment]
当前这个版本不具备保活账号是吧、那得替换release版了、然后7天跑次、
